### ISSUE TITLE
Response status code does not indicate success: 414 (Request-URI Too Large)

### ISSUE THREAD

**Issue by timgaunt** [ChangemakerStudios/Seq.App.YouTrack#14]
I don't think anything has changed but we've started getting errors when sending errors to YouTrack for certain errors:

```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 414 (Request-URI Too Large).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at YouTrackSharp.Issues.IssuesService.<CreateIssue>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Seq.App.YouTrack.YouTrackIssuePoster.<OnAsync>d__6.MoveNext()
```

I'm not sure what you're sending in the url's payload but the log message doesn't look too unusual: `Exception processing Stripe Webhook: Error converting value {null} to type 'System.Int64'. Path 'data.object.status_transitions.paid_at', line 128, position 23.`

**Comment by timgaunt** [comment]
The JSON log is only 19KB

**Comment by waynebrantley** [comment]
We are getting this too for some errors.  The error in question was 301 characters.  Not sure if you are using that in some fashion.

**Comment by timgaunt** [comment]
@Jaben is there anything we can do to help get this resolved? It's blocking most submissions our end atm :(

**Comment by nblumhardt** [comment]
It looks like this might be a YouTrack issue- https://youtrack-support.jetbrains.com/hc/en-us/community/posts/205773099-414-Request-URI-Too-Large-from-Jetty-How-increase-max-header-size-with-Jetty-Youtrack-MSI-distribution- points that way, at least. HTH!

**Comment by Jaben** [comment]
The latest is upgraded to YouTrack new API -- please try it now.

**Comment by timgaunt** [comment]
Have upgraded but get the following error:

```
System.IO.FileNotFoundException: Could not load file or assembly 'Serilog.Formatting.Compact.Reader, Version=1.0.3.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10' or one of its dependencies. The system cannot find the file specified.
File name: 'Serilog.Formatting.Compact.Reader, Version=1.0.3.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'
   at Seq.Apps.GenericHost.AppHost.ReadSerilogEvent(String clef, String& eventId, UInt32& eventType)
   at Seq.Apps.GenericHost.AppHost.<SendTypedEventAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Seq.Apps.GenericHost.AppHost.<SendAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Seq.Apps.GenericHost.Program.<Main>d__0.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

**Comment by nblumhardt** [comment]
Hi Tim; we've seen this one pop up a couple of times - I'm guessing that you're running 5.1.3364?

**Comment by timgaunt** [comment]
> I'm guessing that you're running 5.1.3364?

That's correct @nblumhardt, is there something we can do about it?

**Comment by nblumhardt** [comment]
It's a bit of a puzzle; the latest version appears to work for me with a fresh 5.1.3364 install (I have to use a dummy YouTrack URL, but the part of the code shown in the stack trace above is executed successfully).

My current theory is that it's either GAC or Windows Defender-related.

 * If some other app is adding _Serilog.Formatting.Compact.Reader_ to the GAC, then it should show up under `%WINDIR%\Assembly`.
 * If Windows Defender is "quarantining" the DLL, then running the 5.1.3364 installer again, and selecting "Repair", should fix it.

Do either of these shine any light on it?

**Comment by timgaunt** [comment]
Didn't appear to no. I can't spot anything in the GAC. Seq is the only thing on this server. I didn't think to try adding the folder to the ignores on Windows Defender but upgrading appears to have resolved the issue.

**Comment by nblumhardt** [comment]
Okay, thanks for checking it out - the mystery remains :-) but glad you're up and running! 👍

**Comment by timgaunt** [comment]
I think I spoke too soon sadly as I've found the last few times I've used it I've been getting this error again

```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 414 (Request-URI Too Large).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at YouTrackSharp.Issues.IssuesService.<CreateIssue>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Seq.App.YouTrack.YouTrackIssuePoster.<OnAsync>d__6.MoveNext()
```

The log message I'm sending isn't particularly large (a single exception and a dozen properties).

I've anonymised the data but kept the string lengths in case it helps. Here's the JSON

```
{"@t":"2020-08-04T05:30:18.1662173+01:00","@mt":"Unhandled exception","@m":"Unhandled exception","@i":"3c37575a","@l":"Fatal","@x":"System.InvalidOperationException: There is already an open DataReader associated with this Command which must be closed first.\r\n   at System.Data.SqlClient.SqlInternalConnectionTds.ValidateConnectionForExecute(SqlCommand command)\r\n   at System.Data.SqlClient.SqlConnection.ValidateConnectionForExecute(String method, SqlCommand command)\r\n   at System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)\r\n   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)\r\n   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)\r\n   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)\r\n   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in c:\\Code\\github\\SamSaffron\\MiniProfiler\\StackExchange.Profiling\\Data\\ProfiledDbCommand.cs:line 235\r\n   at System.Data.Common.DbCommand.ExecuteReader()\r\n   at xxxxxxxxxx.DataAccessLayer.Repositories.CategoryRepository.<GetDisplayCategoryTree>b__6_0() in B:\\projects\\xxxxxxxxxxxxxxxx\\src\\xxxxxxxxxxxxxxxx\\xxxxxxxxxx.DataAccessLayer\\Repositories\\CategoryRepository.cs:line 54\r\n   at xxxxxxxxxx.DataAccessLayer.Repositories.CategoryRepository.GetFromCache[T](String objectKey, Func`1 toDoIfNotInCache, Int32 cacheDuration) in B:\\projects\\xxxxxxxxxxxxxxxx\\src\\xxxxxxxxxxxxxxxx\\xxxxxxxxxx.DataAccessLayer\\Repositories\\CategoryRepository.cs:line 39\r\n   at xxxxxxxxxx.DataAccessLayer.Repositories.CategoryRepository.GetDisplayCategoryTree() in B:\\projects\\xxxxxxxxxxxxxxxx\\src\\xxxxxxxxxxxxxxxx\\xxxxxxxxxx.DataAccessLayer\\Repositories\\CategoryRepository.cs:line 49\r\n   at xxxxxxxxxx.Mvc.Indexers.CategoryIndexer.GetCategoryAsDictionary(Category category) in B:\\projects\\xxxxxxxxxxxxxxxx\\src\\xxxxxxxxxxxxxxxx\\xxxxxxxxxx.Mvc\\Indexers\\CategoryIndexer.cs:line 35\r\n   at xxxxxxxxxx.Mvc.Indexers.CategoryIndexer.<GetAllData>d__7.MoveNext() in B:\\projects\\xxxxxxxxxxxxxxxx\\src\\xxxxxxxxxxxxxxxx\\xxxxxxxxxx.Mvc\\Indexers\\CategoryIndexer.cs:line 76\r\n   at Examine.LuceneEngine.Providers.SimpleDataIndexer.PerformIndexAll(String type)\r\n   at Examine.LuceneEngine.Providers.LuceneIndexer.IndexAll(String type)\r\n   at Examine.LuceneEngine.Providers.SimpleDataIndexer.PerformIndexRebuild()\r\n   at Examine.LuceneEngine.Providers.LuceneIndexer.RebuildIndex()\r\n   at xxxxxxxxxx.Mvc.Services.LuceneIndexManager.RecreateIndices() in B:\\projects\\xxxxxxxxxxxxxxxx\\src\\xxxxxxxxxxxxxxxx\\xxxxxxxxxx.Mvc\\Services\\LuceneIndexManager.cs:line 15\r\n   at xxxxxxxxxx.Mvc.Areas.xxxxxxxxxx.Controllers.TasksController.xxxxxxxxxxxxxxxxxx() in B:\\projects\\xxxxxxxxxxxxxxxx\\src\\xxxxxxxxxxxxxxxx\\xxxxxxxxxx.Mvc\\Areas\\xxxxxxxxxx\\Controllers\\TasksController.cs:line 305\r\n   at lambda_method(Closure , ControllerBase , Object[] )\r\n   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)\r\n   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)\r\n   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12()\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)\r\n   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<>c__DisplayClass17.<InvokeActionMethodWithFilters>b__14()\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)\r\n   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<>c__DisplayClass17.<InvokeActionMethodWithFilters>b__14()\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)\r\n   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<>c__DisplayClass17.<InvokeActionMethodWithFilters>b__14()\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodWithFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor, IDictionary`2 parameters)\r\n   at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)\r\n   at System.Web.Mvc.Controller.ExecuteCore()\r\n   at System.Web.Mvc.ControllerBase.Execute(RequestContext requestContext)\r\n   at System.Web.Mvc.ControllerBase.System.Web.Mvc.IController.Execute(RequestContext requestContext)\r\n   at System.Web.Mvc.MvcHandler.<>c__DisplayClass6.<>c__DisplayClassb.<BeginProcessRequest>b__5()\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass1.<MakeVoidDelegate>b__0()\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.<>c__DisplayClass8`1.<BeginSynchronous>b__7(IAsyncResult _)\r\n   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.End()\r\n   at System.Web.Mvc.MvcHandler.<>c__DisplayClasse.<EndProcessRequest>b__d()\r\n   at System.Web.Mvc.SecurityUtil.<GetCallInAppTrustThunk>b__0(Action f)\r\n   at System.Web.Mvc.SecurityUtil.ProcessInApplicationTrust(Action action)\r\n   at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)\r\n   at System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result)\r\n   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()\r\n   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)\r\n   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)","SourceContext":"www.MvcApplication","Exception[0].Type":"System.InvalidOperationException","Exception[0].Message":"There is already an open DataReader associated with this Command which must be closed first.","HttpRequestClientHostIP":"11.222.333.444","HttpRequestClientHostName":"11.222.333.444","HttpRequestId":"e97f6d03-b103-458d-aa1d-40e2816c43a9","HttpRequestNumber":6,"HttpRequestRawUrl":"/xxxxxxxxxx/tasks/xxxxxxxxxxxxxxxxxx","HttpRequestTraceId":"00000000-0000-0000-0000-000000000000","HttpRequestType":"GET","HttpRequestUrl":"https://xxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxx/tasks/xxxxxxxxxxxxxxxxxx","HttpRequestUserAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36","HttpSessionId":"jsrmmon2drhlglgwmqqh5loe","UserName":"(anonymous)","YouTrackId":"xx","SubSystem":"www","HostingEnvironment":"LIVE"}
```

**Comment by Jaben** [comment]
@timgaunt Based on this issue: https://github.com/JetBrains/YouTrackSharp/issues/94 -- I think the "summary" is too large. I'll add a truncate feature.

**Comment by timgaunt** [comment]
You could be onto something with that, I've set the summary template to be `{{$Message}}` and it's posted a couple of tests over fine

**Comment by timgaunt** [comment]
I've had a temporary test and truncated the `Summary` (title) but that hasn't entirely resolved it however if I set both the `Summary` and `Body` templates to something short then it works even for longer errors so I think the length is the issue when there are lots of properties.

For now we'll just remove the properties from the description.

**Comment by timgaunt** [comment]
That only got us so far. We've had to change the exception to report if there is one rather than output if there is.

```
{{#if $Exception}}
#### Exception
Please see the attached json for the stack trace
{{/if}}
```
